export GO111MODULE=on
LDFLAGS := -s -w

all: build

build: app

app:
	env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build  -o ./release/frp_plugin_allowed_ports-darwin-amd64 ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=freebsd GOARCH=386 go build  -o ./release/frp_plugin_allowed_ports-freebsd-386 ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build  -o ./release/frp_plugin_allowed_ports-freebsd-amd64 ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=linux GOARCH=386 go build  -o ./release/frp_plugin_allowed_ports-linux-386 ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  -o ./release/frp_plugin_allowed_ports-linux-amd64 ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=linux GOARCH=arm go build  -o ./release/frp_plugin_allowed_ports-linux-arm ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build  -o ./release/frp_plugin_allowed_ports-linux-arm64 ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=windows GOARCH=386 go build  -o ./release/frp_plugin_allowed_ports-windows-386.exe ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build  -o ./release/frp_plugin_allowed_ports-windows-amd64.exe ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=linux GOARCH=mips64 go build  -o ./release/frp_plugin_allowed_ports-linux-mips64 ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=linux GOARCH=mips64le go build  -o ./release/frp_plugin_allowed_ports-linux-mips64le ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=linux GOARCH=mips GOMIPS=softfloat go build  -o ./release/frp_plugin_allowed_ports-linux-mips ./cmd/frp_plugin_allowed_ports
	env CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build  -o ./release/frp_plugin_allowed_ports-linux-mipsle ./cmd/frp_plugin_allowed_ports
